### ISSUE TITLE
May we have an example of how to use TracingAction with Play 2.6?

### ISSUE THREAD

**Issue by dwo** [lucidsoftware/opentracing-playframework#8]
I'm fairly new to OpenTracing, Scala, Play, and Akka, so apologies if I get any of the terminology wrong.

The `README` currently has an example for setting up a `Filter` (presumably to wrap and trace every HTTP request?) but several of those classes are now deprecated in 0.15. I can see in https://github.com/lucidsoftware/opentracing-playframework/commit/fd8cdc1ad532b3d361772087d4aaaa43e9ccce34 that `DefaultTracingFilter` was deprecated and it says "Filters don't work well for setting thread local storage, use `DefaultTracingAction` instead" (does it mean `DefaultTracingActionBuilder`?).

I'm unsure where I would create the object suggested by the code comments. I have set up a `GlobalTracer` and I can put something like this...
```
object TracingAction extends DefaultTracingActionBuilder(List(new StandardSpanTagger))
```

However, my IDE points out `no implicits found for parameter mat: ActorMaterializer` in the two contexts I've tried this (inside the application's `Loader` and inside a `Controller`).

If it's any help: the context in which I'm trying to do this is the open-source [Kafka Manager](https://github.com/yahoo/kafka-manager), hopefully to get some traces into a local LightStep satellite instance.

**Comment by dwo** [comment]
I asked a local Scala person in my office and they told me I should probably just stick
```
implicit val sys = ActorSystem("whatever")
implicit val mat = ActorMaterializer()
```
in front of my `TracingAction` -- is this the way to go or am I supposed to hook this into the Play application's `ActorSystem`?

I'll be trying this out shortly: if it works I could maybe make a PR to the README?

**Comment by cbrunnkvist** [comment]
How did it go? We seem to currently be utterly under-documented...

**Comment by dwo** [comment]
I did eventually get it all working, here's what I Iearned:

* As seen above, I did need to create implicit `ActorSystem` and `ActorMaterializer` to create my `object TracingAction` -- not sure if this is the best practice but it does work?
* You have to watch out for some transitive dependencies relating to `opentracing-thread-context`: [this line](https://github.com/lucidsoftware/opentracing-thread-context/blob/0.4/thread-context/src/main/java/io/opentracing/threadcontext/ContextSpan.java#L7) was failing (ClassNotFound) because `opentracing-java` [changed it's package](https://github.com/opentracing/opentracing-java/commit/6dee0c92792bd778aa35002ae68cdabaeb8ed695#diff-66007c7050bb34a860d15743bb396767) from `io.opentracing` to `io.opentracing.noop`. I was getting a newer version throught my `lightstep-tracer-jre` and had to pin lightstep back from `0.16.4` to `0.11.1` in order to get a working set of dependencies (ie. keeping `opentracing-noop` back on 0.20.7).
* The docs say to set your `akka.actor.default-dispatcher.type` to 
```
com.lucidchart.akka.threadcontext.DefaultDispatchConfigurator
```
  however, the correct class name is 
```
com.lucidchart.akka.threadcontext.DefaultDispatcherConfigurator
``` 
  (`Dispatch_er_Configurator` not `DispatchConfigurator`)

There's a few minor corrections I could submit here, and maybe even an example if I got this all vaguely right?

I think the dependency problem maybe needs to be reported on `opentracing-thread-context`? I'll raise something there.
